"""Smoke test for the comprehensive planner."""
import asyncio
from ai_pc_operator.backend.app.agent.planner import Planner


async def main():
    p = Planner()
    tests = [
        "close all apps in desktop",
        "close all apps in taskbar",
        "close chrome",
        "shut down chrome",
        "kill all apps",
        "keep chrome open but close everything else",
        "open chrome",
        "search best air coolers",
        "check my pc status",
        "list files in downloads",
        "open youtube",
        "open github.com",
        "browser session",
        "keep awake for 30 minutes",
        "open settings for contrast",
        "lock my pc",
        "restart my pc",
        "shutdown my pc",
        "take a screenshot",
        "ping google.com",
        "compose email to alice@example.com",
        "remember that my favorite color is blue",
        "research AMD ROCm",
        "git clone repo",
        "docker build",
        "read pdf",
        "open excel",
        "close notepad",
        "minimize window",
        "maximize window",
        "arrange windows",
        "install vscode",
        "uninstall chrome",
        "update spotify",
        "restart discord",
        "run powershell command",
        "run cmd",
        "build project",
        "run tests",
        "run dev server",
        "read text on screen",
        "detect buttons",
        "copy to clipboard",
        "paste from clipboard",
        "read clipboard",
        "send email",
        "search email",
        "download file",
        "upload file",
        "check wifi",
        "record screen",
        "open camera",
        "create pdf",
        "read word document",
        "read excel spreadsheet",
        "read csv file",
        "forget that",
        "create task",
        "run task",
        "cancel task",
        "summarize article",
        "what is my pc status",
        "show me disk usage",
        "how much memory am i using",
        "delete files in downloads",
        "open notepad",
        "open calculator",
        "open file explorer",
        "open paint",
        "open settings",
        "open control panel",
        "open task manager",
        "open registry editor",
        "open device manager",
        "open disk management",
        "open event viewer",
        "open services",
        "open notepad++",
        "open sublime text",
        "open atom",
        "open vim",
        "open emacs",
        "open photoshop",
        "open illustrator",
        "open premiere",
        "open after effects",
        "open blender",
        "open unity",
        "open unreal",
        "open docker",
        "open vmware",
        "open virtualbox",
        "open obs",
        "open streamlabs",
        "open zoom",
        "open teams",
        "open skype",
        "open vlc",
        "open media player",
        "open photos",
        "open snipping tool",
        "open sticky notes",
        "open onenote",
        "open todo",
        "open mail",
        "open calendar",
        "open maps",
        "open weather",
        "open store",
        "open xbox",
        "open groove music",
        "open movies",
        "open 3d builder",
        "open 3d viewer",
        "open alarms",
        "open camera app",
        "open cortana",
        "open feedback hub",
        "open get help",
        "open mixed reality",
        "open mobile plans",
        "open money",
        "open news",
        "open office",
        "open people",
        "open phone",
        "open projecting to this pc",
        "open security",
        "open tips",
        "open voice recorder",
        "open wallet",
        "open your phone",
    ]
    passed = 0
    failed = 0
    for t in tests:
        intent = await p.classify_intent(t)
        plan = await p.create_plan(t, intent)
        steps = plan.get("steps", [])
        if steps:
            tools = [s.get("tool", "?") for s in steps]
            print(f"  {t!r:55s} -> {intent:25s} -> {tools}")
            passed += 1
        else:
            err = plan.get("error", "")[:80]
            print(f"  {t!r:55s} -> {intent:25s} -> NO STEPS ({err})")
            failed += 1
    print()
    print(f"PASSED: {passed}")
    print(f"FAILED: {failed}")
    print(f"TOTAL:  {passed + failed}")


asyncio.run(main())
